import React, { useState } from 'react';
import { 
  ShieldCheck, 
  AlertTriangle, 
  Clock, 
  FileText, 
  Share2, 
  Download, 
  Scale, 
  Check, 
  Printer, 
  ArrowLeft,
  Sparkles,
  ExternalLink,
  Info
} from 'lucide-react';
import { PolicyAnalysis } from '../types';

interface ScorecardHeaderProps {
  analysis: PolicyAnalysis;
  onBackToDashboard: () => void;
  onOpenCompare: () => void;
}

export const ScorecardHeader: React.FC<ScorecardHeaderProps> = ({
  analysis,
  onBackToDashboard,
  onOpenCompare
}) => {
  const [copied, setCopied] = useState(false);

  const isLow = analysis.riskLevel === 'Low';
  const isModerate = analysis.riskLevel === 'Moderate';
  const isHigh = analysis.riskLevel === 'High';

  const riskBadgeStyle = isLow 
    ? 'text-emerald-700 bg-emerald-50 border-emerald-300' 
    : isModerate 
    ? 'text-amber-700 bg-amber-50 border-amber-300' 
    : 'text-rose-700 bg-rose-50 border-rose-300';

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportMarkdown = () => {
    const md = `# PrivacyLens Policy Insights: ${analysis.serviceName}
AI-generated Privacy Risk Indicator: ${analysis.riskLevel} (${analysis.riskScore}/100)
Analyzed: ${analysis.analyzedAt}
Category: ${analysis.serviceCategory}
Notice: ${analysis.disclaimer}

## Executive Verdict
${analysis.oneSentenceVerdict}

## Data Collected
${analysis.executiveSummary.dataCollected.map(d => `- ${d}`).join('\n')}

## Third-Party Data Sharing
${analysis.executiveSummary.dataShared.map(d => `- ${d}`).join('\n')}

## Important Clauses (${analysis.importantClauses?.length || analysis.redFlags?.length || 0})
${(analysis.importantClauses || analysis.redFlags).map(c => `### [${c.severity.toUpperCase()}] ${c.title}
*Clause Excerpt:* "${c.clauseExcerpt}"
*Summary:* ${c.explanation}
*Impact:* ${c.riskImpact}
`).join('\n')}

## Opt-Out Guidance
${analysis.optOutGuidance?.steps?.map(s => `${s.step}. **${s.action}**: ${s.description}`).join('\n') || 'Review app settings for personalized ad toggles.'}

---
Generated by PrivacyLens - See what your data really means
*Informational AI-generated assessment; not a legal conclusion or legal advice.*
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${analysis.serviceName.toLowerCase()}-privacy-insights.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6 sm:p-8 relative overflow-hidden space-y-6">
      
      {/* Top action row */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-5 border-b border-slate-100">
        <button
          onClick={onBackToDashboard}
          className="flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-900 transition-colors cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Dashboard</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={onOpenCompare}
            className="px-3 py-1.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 flex items-center gap-1.5 cursor-pointer"
          >
            <Scale className="w-3.5 h-3.5 text-indigo-500" />
            <span>Compare</span>
          </button>

          <button
            onClick={handleExportMarkdown}
            className="px-3 py-1.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 flex items-center gap-1.5 cursor-pointer"
            title="Download report as Markdown"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export Report</span>
          </button>

          <button
            onClick={handleShare}
            className="px-3 py-1.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 flex items-center gap-1.5 cursor-pointer"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-600" />
                <span className="text-emerald-700">Link Copied!</span>
              </>
            ) : (
              <>
                <Share2 className="w-3.5 h-3.5" />
                <span>Share</span>
              </>
            )}
          </button>

          <button
            onClick={() => window.print()}
            className="p-1.5 rounded-lg border border-slate-200 text-slate-500 hover:text-slate-800 hover:bg-slate-50 cursor-pointer hidden sm:block"
            title="Print Report"
          >
            <Printer className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Main Scorecard Body */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
        
        {/* Company & Details */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="px-2.5 py-0.5 rounded-md bg-indigo-50 border border-indigo-200/60 text-indigo-700 text-[11px] font-bold uppercase tracking-wider">
              {analysis.serviceCategory}
            </span>
            {analysis.id.startsWith('sample-') && (
              <span className="px-2 py-0.5 rounded-md bg-amber-50 border border-amber-200 text-amber-800 text-[11px] font-bold uppercase tracking-wider">
                Demo Data
              </span>
            )}
            <span className="text-xs text-slate-400">•</span>
            <span className="text-xs text-slate-500">
              Analyzed {analysis.analyzedAt}
            </span>
            {analysis.policyUrl && (
              <>
                <span className="text-xs text-slate-400">•</span>
                <a
                  href={analysis.policyUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="text-xs text-indigo-600 hover:underline inline-flex items-center gap-1"
                >
                  Source Policy
                  <ExternalLink className="w-3 h-3" />
                </a>
              </>
            )}
          </div>

          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
            {analysis.serviceName}
          </h1>
          {analysis.companyName && (
            <p className="text-sm font-medium text-slate-500">
              Governed by {analysis.companyName}
            </p>
          )}

          {/* Reading Time Saved Badge */}
          <div className="pt-1 flex items-center gap-3 text-xs text-slate-600 flex-wrap">
            <span className="inline-flex items-center gap-1.5 font-semibold text-indigo-700 bg-indigo-50/80 px-2.5 py-1 rounded-md border border-indigo-200/60">
              <Clock className="w-3.5 h-3.5" />
              Saved ~{analysis.readingTimeMinutesSaved} mins of legal reading
            </span>
            <span className="text-slate-400">
              (~{analysis.wordCount.toLocaleString()} words analyzed)
            </span>
          </div>
        </div>

        {/* AI-Generated Privacy Risk Indicator */}
        <div className="flex items-center gap-5 bg-slate-50 p-5 rounded-2xl border border-slate-200/80 self-start lg:self-center">
          <div className={`px-4 py-3 rounded-2xl flex flex-col items-center justify-center font-black border-2 shadow-xs ${riskBadgeStyle}`}>
            <span className="text-xl leading-none uppercase">{analysis.riskLevel}</span>
            <span className="text-[10px] font-bold tracking-wider mt-1 opacity-80">RISK</span>
          </div>

          <div className="space-y-1">
            <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
              AI-generated Privacy Risk Indicator
            </span>
            <div className="flex items-baseline gap-1.5">
              <span className="text-2xl font-black text-slate-900">{analysis.riskScore}</span>
              <span className="text-xs font-semibold text-slate-400">/ 100</span>
            </div>
            <p className="text-[11px] text-slate-500 max-w-[210px] leading-tight">
              {isLow 
                ? 'Minimal telemetry and strong consumer data retention safeguards.'
                : isModerate 
                ? 'Standard commercial tracking with optional opt-out toggles.'
                : 'Extensive tracking, biometric extraction, or third-party sharing detected.'}
            </p>
          </div>
        </div>

      </div>

      {/* One-Sentence Verdict Callout */}
      <div className="p-4 rounded-xl bg-indigo-50/60 border border-indigo-100 flex items-start gap-3">
        <Sparkles className="w-5 h-5 text-indigo-600 shrink-0 mt-0.5" />
        <div className="space-y-1 flex-1">
          <p className="text-xs font-bold text-indigo-900 uppercase tracking-wider">
            Executive Summary
          </p>
          <p className="text-xs sm:text-sm text-slate-800 font-medium leading-relaxed">
            {analysis.oneSentenceVerdict}
          </p>
        </div>
      </div>

      {/* Informational Disclaimer Notice */}
      <div className="flex items-center gap-2 text-[11px] text-slate-500 bg-slate-50 px-3 py-2 rounded-xl border border-slate-200/70">
        <Info className="w-3.5 h-3.5 text-slate-400 shrink-0" />
        <span>
          {analysis.id.startsWith('sample-')
            ? 'These examples are demonstration data and do not represent an official legal or privacy assessment of the listed services.'
            : 'Informational AI Assessment: PrivacyLens provides automated summaries for informational convenience. It is not a legal conclusion and does not constitute legal advice.'}
        </span>
      </div>

    </div>
  );
};
